### ISSUE TITLE
Add autoscaling

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/openedx-k8s-harmony#2]

**Comment by adzuci** [comment]
Hey @bradenmacdonald, in case it's helpful, this is an example of how 2U defines an HPA in a Django IDA chart:

```

{{ if and .Values.app.enabled .Values.app.autoscaling.enabled}}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  minReplicas: {{ .Values.app.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.app.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  targetCPUUtilizationPercentage: {{ .Values.app.autoscaling.targetCPUUtilizationPercentage }}

{{ end }}
```
